### ISSUE TITLE
Xerses option for jackknife output before mean and average

### ISSUE THREAD

**Issue by giulioisac** [poseidon-framework/poseidon-analysis-hs#18]
Hello,

It would be great to have the option in the fstat command to output the value of the statistic for each block instead of mean and variance from jackknife. 
A possibility would be to also output the beginning and the end of the relative positions in the genomes for each block of SNPs, so that values of the F2 can be compared across different samples.
Is this already possible in some way? I cannot find it in the documentation. 

Thanks!
Best,
Giulio

**Comment by stschiff** [comment]
Yes, I agree. The other command `ras` can already do this. I can implement for Xerxes as well. Thanks for the feedback

**Comment by stschiff** [comment]
Done in the latest version 0.3.2.0. Note that the per-block output is not in every sense the "raw" data before the Jackknifing operation. I can explain in more detail in person, and I'm also working on a little Math writeup to add to this repo.

**Comment by giulioisac** [comment]
That will help, thanks!
