### ISSUE TITLE
Integration into poseidon-hs

### ISSUE THREAD

**Issue by nevrome** [poseidon-framework/poseidon-analysis-hs#21]
To simplify our development processes and make sure that everything is always in sync we decided already a while ago to integrate poseidon-analysis-hs into poseidon-hs. This is certainly a risky experiment, but I'm optimistic that it will pay off.

Doing this will pretty much immediately solve #6 and #16, make implementing #10 trivial and make it more easy to be consequent with #8.

Before this integration I should complete #17.

**Comment by stschiff** [comment]
Yes, thank your for putting this here. I am looking forward to doing this (and I feel I should be doing it)

**Comment by stschiff** [comment]
For the record, we decided not to do this for the time being. I'm gonna close this for now.
